n = input("digite aqui :")
print(n.isnumeric(n))
print(n.isalnum(n))
print(n.isalpha(n))
print(n.isascii(n))
print(n.isdecimal())
print(n.isdigit(n))
print(n.isidentifier(n))
print(n.islower(n))
print(n.isnumeric(n))
print(n.isprintable(n))
print(n.isspace(n))
print(n.istitle(n))
print(n.isupper(n))
